### PR TITLE
Add null check

### PR DESCRIPTION
**Pull request by nekolaboratory**
ref: https://developer.android.com/reference/android/content/ClipboardManager#getPrimaryClip()

### CODE REVIEW

**Review by koral-- — APPROVED** [review]

**Comment by koral--** [comment]
LGTM but please add a sign-off in order for DCO to pass.

**Comment by nekolaboratory** [comment]
Thank you very much for the notice.

**Comment by nekolaboratory** [comment]
Hello @koral-- .
This time, I originally put a null check in the place where null can pass, but with the additional change, the check of hasPrimaryClip became redundant, so I deleted it.
I think this function should be used anywhere other than using getPrimaryClip and checking the result directly.
Do you think it makes sense to merge this?

**Comment by koral--** [comment]
I think it is slightly better to use only `getPrimaryClip` and nulcheck instead of `hasPrimaryClip` followed by `getPrimaryClip`.
If the clip becomes null in the time between `has` and `get` calls we will get a NPE. So your changes are worth merging.

Build fails due to lint check about target SDK too old to be published in the Play Store. I'll fix that on develop and then rebase this PR.

**Pull request merged**
