### PR TITLE
[WIP]Fix: GET_CLIPBOARD fails on Android 11 #51

### PR DESCRIPTION
**Pull request by nekolaboratory**
Signed-off-by: Yusuke Arakawa <nekolaboratory@users.noreply.github.com>

### CODE REVIEW

**Comment by DonVietnam** [comment]
@nekolaboratory  So, in order to use this solution correctly, do I need to grant rights to READ_LOGS via adb?

**Comment by nekolaboratory** [comment]
Yes, that's right.
In addition to adding permissions for READLOGS, I envision forcing the process to restart after giving permission to bring the window to the foreground.

```
adb -d shell pm grant jp.co.cyberagent.stf android.permission.READ_LOGS;
adb -d shell appops set jp.co.cyberagent.stf SYSTEM_ALERT_WINDOW allow;
adb -d shell am force-stop jp.co.cyberagent.stf;
```

**Comment by DonVietnam** [comment]
@nekolaboratory I tried to use app with your changes on my android 11, realme x2, but have the same problem, i get null for every clipboard content request.

**What have i done:**

1. Build app.
2. Replace app in my device with new one.
3. Grant all permissions via ADB.
4. Launch STF.
5. Check app version on device, it was the same, so stf did not replace new version.
6. Tried to get clipboard data.
7. Got null.

Please, let me know if i do something wrong.

**Comment by nekolaboratory** [comment]
I was able to get an android 13 pixel6a terminal, so when I debugged it, I discovered that it didn't behave as intended.
This is because Android 12 is affected by security restrictions.
https://developer.android.com/about/versions/12/behavior-changes-all?hl=ja#untrusted-touch-events

I'm sorry, but I will withdraw this PR once considering the availability of STF in the future.

**Pull request closed without merging**
